server {
	listen 80;
    listen [::]:80;
	server_name whizvoice.com www.whizvoice.com;
    location ~ /.well-known {
        root /var/www/whizvoice/whizvoice.com;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
	server_name whizvoice.com www.whizvoice.com;
    ssl_certificate /etc/letsencrypt/live/whizvoice.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/whizvoice.com/privkey.pem; # managed by Certbot
    
    # WebSockets proxy - Moved before static files
    location /ws/ {
        proxy_pass http://127.0.0.1:8000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 86400;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    # API Server proxy
    location /api/ {
        proxy_pass http://127.0.0.1:8000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    # Static website - Moved after WebSocket and API
    location / {
        root /var/www/whizvoice/whizvoice.com;
        index index.html;
    }
}