
server {
	listen 80;
    listen [::]:80;
	server_name whizvoice.com www.whizvoice.com;
    location ~ /.well-known {
        root /var/www/whizvoice/whizvoice.com;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
	server_name whizvoice.com www.whizvoice.com;
    ssl_certificate /etc/letsencrypt/live/whizvoice.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/whizvoice.com/privkey.pem; # managed by Certbot
    location / {
        root /var/www/whizvoice/whizvoice.com;
        index index.html;
    }

}